### ISSUE TITLE
LOAD DATA LOCAL INFILE - File not found

### ISSUE THREAD

**Issue by XSHui** [pingcap/tidb-bench#39]
I'm having a problem with tidb
When I try to exec load_data.sh error like below appeared

load data error:
```
ERROR 2 (HY000) at line 1: File '*****/tools/web_sales.dat' not found (Errcode: 2)
ERROR 2 (HY000) at line 1: File '*****/tools/web_site.dat' not found (Errcode: 2)
```

tidb version : 2.0.4
os : centos 7.2

**Comment by XSHui** [comment]
@zhangjinpeng1987

**Comment by zhangjinpeng1987** [comment]
@XSHui Sorry for the late reply, how did you fix it?
